export const servicesList = [
  {
    id: 1,
    category: "Digital Life",
    name: "Paying Bills",
    description: "We pay your utility bills online safely.",
    icon: "groceries.png",
    formFields: ["Bill Type", "Amount"],
  },
  {
    id: 2,
    category: "Digital Life",
    name: "Book Uber/Ola",
    description: "Book rides conveniently in your city.",
    icon: "uber.png",
    formFields: ["Pickup Location", "Drop Location", "Time"],
  },
  {
    id: 3,
    category: "Digital Life",
    name: "Order Medplus/BigBasket",
    description: "Order groceries or medicines online.",
    icon: "groceries.png",
    formFields: ["Items List", "Delivery Date", "Address"],
  },
  {
    id: 4,
    category: "Digital Health",
    name: "WhatsApp Video Calls",
    description: "Setup video calls with doctors/family.",
    icon: "whatsapp.png",
    formFields: ["Doctor/Family Name", "Date & Time", "Notes"],
  },
  {
    id: 5,
    category: "Digital Health",
    name: "Organize Digital Health Records",
    description: "We help manage and organize your medical records online.",
    icon: "doctor.png",
    formFields: ["Record Type", "Upload File (optional)"],
  },
  {
    id: 6,
    category: "Digital Safety",
    name: "Home CCTV Setup",
    description: "Setup home CCTV and teach usage.",
    icon: "camera.png",
    formFields: ["CCTV Model", "Address"],
  },
  {
    id: 7,
    category: "Digital Safety",
    name: "WiFi / Device Setup",
    description: "Ensure your devices and WiFi are working properly.",
    icon: "wifi.png",
    formFields: ["Device Type", "Problem Description"],
  },
  {
    id: 8,
    category: "Digital Life",
    name: "Printer / Phone Troubleshooting",
    description: "We fix common printer and phone issues.",
    icon: "printer.png",
    formFields: ["Device Type", "Issue Description"],
  },
  {
    id: 9,
    category: "Tech Check",
    name: "Weekly Tech-Check Visit",
    description: "A technician visits once a week to check devices and WiFi.",
    icon: "techcheck.png",
    formFields: ["Preferred Day & Time"],
  },
];
